apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/nickhstr/todo-rust.git
    targetRevision: HEAD
    path: deploy/argocd/manifests/todo-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app-staging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true, CreateNamespace=true]
