---
apiVersion: v1
kind: Namespace
metadata:
  name: smoke
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smoke-test
  namespace: smoke
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: smoke-test
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: smoke-test
        property: secret
