apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect-connect.onepassword-connect.svc.cluster.local:8080
      vaults:
        todo-app: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-access-token
            namespace: onepassword-connect
            key: token
