apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-postgres
spec:
  instances: 1
  storage:
    size: 512Mi
    storageClass: local-path # k3d default
  resources:
    requests: { cpu: 25m, memory: 128Mi }
    limits: { cpu: 500m, memory: 512Mi }
