apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-local

resources:
  - namespace.yaml
  - ../../base
  - session-key-secret.yaml

patches:
  - path: patches.yaml
  - path: cnpg-cluster-patch.yaml

images:
  - name: todo-app
    newName: ghcr.io/nickhstr/todo-app
    newTag: bootstrap
