apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  sources:
    - repoURL: https://1password.github.io/connect-helm-charts
      chart: connect
      targetRevision: 1.16.0
      helm:
        valueFiles:
          - $values/deploy/argocd/manifests/platform/onepassword-connect/values.yaml
    - repoURL: https://github.com/nickhstr/todo-rust.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword-connect
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true, CreateNamespace=true]
