apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nickhstr/todo-rust.git
    targetRevision: HEAD
    path: deploy/argocd/manifests/smoke
  destination:
    server: https://kubernetes.default.svc
    namespace: smoke
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true, CreateNamespace=true]
